import { ReactNode } from "react";
import { Inter } from "next/font/google";
import { Metadata } from "next";
import { MSWProvider } from "@/app/_component/MSWComponent";
import "./globals.css";
import AuthSession from "./_component/AuthSession";

if (
  process.env.NEXT_RUNTIME === "nodejs" &&
  process.env.NODE_ENV !== "production" &&
  process.env.NEXT_PUBLIC_MSW_ENABLED !== "false"
) {
  const { server } = require("@/mocks/http");
  server.listen();
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create-next-app",
};

type Props = {
  children: ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MSWProvider>
          <AuthSession>{children}</AuthSession>
        </MSWProvider>
      </body>
    </html>
  );
}
